module VerifyExamples.Accessors.Name0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Accessors exposing (..)
import Lens as L
import Accessors.Library exposing (..)
import Accessors exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#name: \n\n    name (L.email << try << L.info << dictEntry \"subject\")\n    --> \".email?.info{}\"" <|
        \() ->
            Expect.equal
                (
                name (L.email << try << L.info << dictEntry "subject")
                )
                (
                ".email?.info{}"
                )